version: "3.6"
services:
  mysql:
    image: mysql/mysql-server:latest-aarch64
    # command: mysqld --default-authentication-plugin=mysql_native_password
    command: mysqld --default-authentication-plugin=mysql_native_password --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql:rw
    networks:
      - database-net
    env_file:
      - ./database/database.env
    restart: always
  redis:
    image: redis
    container_name: redis 
    ports:
      - "6379:6379"
    expose:
      - 6379
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
        # - PMA_ARBITRARY=1
        - PMA_HOST=mysql
    restart: always
    ports:
        - 8080:80
    # volumes:
        # - ./pma-sessions:/sessions
    networks: 
      - database-net
  # nginx:
  #   image: nginx:${NGINX_VERSION:-latest}
  #   container_name: nginx
  #   networks:
  #     - nginx-net
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - /home/kiiotory/OwnProjects/digital-ocean/prazdnik/wordpress:/var/www/wp-prazdnik
  #     - ${NGINX_CONF_DIR:-./nginx/conf.d}:/etc/nginx/conf.d
  #     - ${NGINX_CONF_DIR:-./.htpasswd}:/etc/nginx/.htpasswd
  #     # - ${NGINX_LOG_DIR:-../logs/nginx}:/var/log/nginx
  #     - ${SSL_CERTS_DIR:-./certs}:/etc/letsencrypt
  #     - ${SSL_CERTS_DATA_DIR:-./certs-data}:/data/letsencrypt
  #   restart: always
# volumes:
#   wordpress:
networks:
  nginx-net:
    name: nginx-net
    driver: bridge
  database-net:
    name: database-net
    driver: bridge